name: Merge upstream

on: workflow_dispatch

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        id: merge-upstream
        with:
          upstream: myoung34/docker-github-actions-runner
          upstream-branch: main
          branch: master
          token: ${{ secrets.TOKEN }}
        continue-on-error: true
      - name: Check if any change merged
        if: ${{ steps.merge-upstream.outcome }} == 'failure'
        run: echo 'No changes merged. Skipping.'; exit 0
      - name: Build Docker image
        run: echo 'TODO build Docker image'
