name: Merge upstream

on: workflow_dispatch

jobs:
  scan:
    name: List Recent Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan Docker Repository
        uses: dhet/scan-docker-tags-action@v1.0.1
        with:
          image: myoung34/github-runner
          max-age-minutes: 15
          tag-regex: ^\\d+\\.\\d+\\.\\d+$
          username: horca
          password: ${{ secrets.DOCKER_PASS }}
        id: scan
      - name: Print
        run: "echo 'Recent updates: ${{ steps.scan.outputs.tags }}'"
