name: Build, push and deploy new GitHub runner image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-runner-image:
    name: Build new runner image
    runs-on: ubuntu-latest
    steps:
      - name: Print tag
        run: echo ${{ inputs.tag }}
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
